### ISSUE TITLE
I can not see it with the tc command

### ISSUE THREAD

**Issue by yuniannn** [thombashi/tcconfig#94] opened 2018-01-31 07:01 UTC
I installed by pip.

I used tcset to do the following
$ tcset --device eth0 --rate 400k --src-network 10.211.55.22/32 --direction incoming --add

It works well.

However, I can not confirm anything using the tc command.
$ tc class show dev eth0
$ tc filter show dev eth0

And one more thing, if I set the --port to the incoming direction, it does not work well. what's the reason?

OS Version: CentOS7.2

I wonder why.
Thanks.

**Comment by thombashi** [comment] 2018-02-03 14:36
@yuniannn 

>However, I can not confirm anything using the tc command.
>$ tc class show dev eth0
>$ tc filter show dev eth0

The shaping rule for incoming packets is setting up to an ifb device (automatically created by tcset)
You could see the tc settings for incoming packets by the following commands (ifb device name would differ for each network interface name):

```
# tc class show dev ifb8071
class htb 1f87:1 root prio 0 rate 32Gbit ceil 32Gbit burst 0b cburst 0b
class htb 1f87:2 root leaf 2007: prio 0 rate 400Kbit ceil 400Kbit burst 5Kb cburst 5Kb
# tc filter show dev ifb8071
filter parent 1f87: protocol ip pref 2 u32
filter parent 1f87: protocol ip pref 2 u32 fh 800: ht divisor 1
filter parent 1f87: protocol ip pref 2 u32 fh 800::800 order 2048 key ht 800 bkt 0 flowid 1f87:2
  match 00000000/00000000 at 16
  match 0ad33716/ffffffff at 12
# tc qdisc show dev ifb8071
qdisc htb 1f87: root refcnt 2 r2q 10 default 1 direct_packets_stat 0 direct_qlen 32
qdisc netem 2007: parent 1f87:2 limit 1000
```

However, I would recommend to use tcshow which pretty print tcset configurations:

```
# tcshow -d ens33
{
    "ens33": {
        "outgoing": {},
        "incoming": {
            "src-network=10.211.55.22/32, protocol=ip": {
                "filter_id": "800::800",
                "rate": "400K"
            }
        }
    }
}
```

>And one more thing, if I set the --port to the incoming direction, it does not work well. what's the reason?

The `--port` option to the incomming direction had worked in my environment (Fedora 24, iproute 4.10.0-1).
Could you possibly provide the following information?:

- Testing procedure
- Linux kernel version: `uname -a`
- iproute package version: `rpm -qa iproute*`

**Comment by yuniannn** [comment] 2018-02-05 06:49
@thombashi 
Thank you for reply!!

Linux kernel version: 
Linux localhost 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

iproute package version: 
iproute-3.10.0-74.el7.x86_64

And.. In case of incoming, can you briefly explain why you are creating another interface?

**Comment by thombashi** [comment] 2018-02-05 14:09
Thank you for your additional information.

I'm not sure the cause of the problem for now, this may take time.
At a quick look, iproute2 package does not fix bugs for port filtering.
In the meantime, it is very helpful if you could show me your testing procedure (command sequences, application names, etc) to solve the issue.

>And.. In case of incoming, can you briefly explain why you are creating another interface?

You would need ifb device (and ifb kernel module) to shaping traffic for incoming packets.
You could find further information at [networking:ifb [Linux Foundation Wiki]](https://wiki.linuxfoundation.org/networking/ifb)

**Comment by yuniannn** [comment] 2018-02-12 07:45
@thombashi Thank you for your replay.
There was my mistake in specifying the port. :(
It work very well. I am sorry.

**Comment by thombashi** [comment] 2018-03-10 02:46
@yuniannn 
Thank you for your confirmation.
I'll close the issue then.

**Closed by thombashi** 2018-03-10 02:46 UTC
