### ISSUE TITLE
Traceback when using tcset with --change

### ISSUE THREAD

**Issue by selimt** [thombashi/tcconfig#85] opened 2017-08-18 17:03 UTC
To reproduce:

```
tcdel -d eth0
tcset --device eth0 --rate 10M --src-network 172.17.0.2 --direction outgoing
tcset --device eth0 --rate 100M --src-network 172.17.0.2 --direction outgoing --change
```

Output:

```
[DEBUG] subprocrunner: tc qdisc show dev eth0
Traceback (most recent call last):
  File "/usr/local/bin/tcset", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/tcconfig/tcset.py", line 432, in main
    return_code = tc.set_tc()
  File "/usr/local/lib/python3.6/site-packages/tcconfig/traffic_control.py", line 348, in set_tc
    return self.__shaper.set_shaping()
  File "/usr/local/lib/python3.6/site-packages/tcconfig/shaper/htb.py", line 211, in set_shaping
    self._set_netem()
  File "/usr/local/lib/python3.6/site-packages/tcconfig/shaper/_interface.py", line 91, in _set_netem
    "handle {:s}".format(handle),
ValueError: Unknown format code 's' for object of type 'int'
```

tcconfig version is 0.13.2
Although the traceback is produced the change still takes effect.

Thanks

**Comment by thombashi** [comment] 2017-08-19 00:12
@selimt 
Thank you for your report.

The problem was fixed in the latest version (`0.14.0`).
Please upgrade tcconfig (`pip install tcconfig --upgrade`) and re-execute the commands.

**Comment by selimt** [comment] 2017-08-19 00:14
Thank you!

**Comment by selimt** [comment] 2017-08-19 00:16
Hmm, I am still seeing the problem with 0.14.0:
```
root@1d0040e72239:/opt/shaper# tcset --version
tcset 0.14.0
root@1d0040e72239:/opt/shaper# tcset --device eth0 --rate 10M --direction outgoing --change
Traceback (most recent call last):
  File "/usr/local/bin/tcset", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/tcconfig/tcset.py", line 407, in main
    return_code = tc.set_tc()
  File "/usr/local/lib/python3.6/site-packages/tcconfig/traffic_control.py", line 352, in set_tc
    return self.__shaper.set_shaping()
  File "/usr/local/lib/python3.6/site-packages/tcconfig/shaper/htb.py", line 211, in set_shaping
    self._set_netem()
  File "/usr/local/lib/python3.6/site-packages/tcconfig/shaper/_interface.py", line 91, in _set_netem
    "handle {:s}".format(handle),
ValueError: Unknown format code 's' for object of type 'int'
```

**Comment by thombashi** [comment] 2017-08-19 01:54
@selimt
Sorry, I have misunderstood the problem.
Now, I believe the problem fixed in `tsconfig 0.14.1`.
Could you try this version?

**Comment by dastergon** [comment] 2017-09-04 13:17
I can confirm that it works with the latest `tcconfig` version

**Comment by thombashi** [comment] 2017-09-05 12:14
@dastergon 
Thank you for confirmation.

@selimt 
I'll close the issue for now.
Feel free to reopen.

**Closed by thombashi** 2017-09-05 12:14 UTC
Labels: bug
