### ISSUE TITLE
ipaddress package missing from requirements.txt

### ISSUE THREAD

**Issue by fjarrett** [thombashi/tcconfig#78] opened 2017-07-29 02:07 UTC
I installed via `pip install tcconfig` and got the error:

```
ImportError: No module named ipaddress
```

It's listed as a required package [in the docs](http://tcconfig.readthedocs.io/en/latest/pages/installation.html#python-packages), but is missing from `requirements.txt`. Easily fixed, but unexpected :-)

**Comment by thombashi** [comment] 2017-07-29 12:03
@fjarrett 
Thank you for your report.

Would you tell me the following information to understand your situation?

- Python version
- Python interpreter

## Python version
`sys.version_info` would be preferable:

```
$ python
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

In `tcconfig`, `ipaddress` not described in `requirements.txt` but `setup.py` to install the package only for specific versions (Python 2 / older than Python 3.3 ):

```python
if any([
    sys.version_info.major < 3,
    sys.version_info.major == 3 and sys.version_info.minor < 3,
]):
    install_requires.append("ipaddress")
```

`ipaddress` package included in Python standard libraries since Python 3.3 (i.e. not required to install external package).

I assume the above process not properly worked for your environment.

## Python interpreter
CPython, PyPy, or any other interpreters?

**Comment by fjarrett** [comment] 2017-07-29 15:19
> I assume the above process not properly worked for your environment.

Correct, that logic did not appear to work on my setup.

```
$ python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version_info
sys.version_info(major=2, minor=7, micro=5, releaselevel='final', serial=0)
>>> import platform
>>> platform.python_implementation()
'CPython'
```

### Dependency tree

```
$ pipdeptree -p tcconfig
tcconfig==0.12.1
  - DataProperty [required: >=0.25.0, installed: 0.25.1]
    - logbook [required: >=1.1.0, installed: 1.1.0]
    - typepy [required: >=0.0.14, installed: 0.0.14]
      - enum34 [required: Any, installed: 1.1.6]
      - mbstrdecoder [required: >=0.2.2, installed: 0.2.2]
        - six [required: >=1.10, installed: 1.10.0]
      - python-dateutil [required: >=2.6.1, installed: 2.6.1]
        - six [required: >=1.5, installed: 1.10.0]
      - pytz [required: >=2017.2, installed: 2017.2]
      - six [required: >=1.10, installed: 1.10.0]
  - logbook [required: Any, installed: 1.1.0]
  - pyparsing [required: >=2.2.0, installed: 2.2.0]
  - six [required: Any, installed: 1.10.0]
  - subprocrunner [required: >=0.8.4, installed: 0.8.4]
    - logbook [required: >=1.1.0, installed: 1.1.0]
    - mbstrdecoder [required: Any, installed: 0.2.2]
      - six [required: >=1.10, installed: 1.10.0]
    - six [required: Any, installed: 1.10.0]
    - typepy [required: >=0.0.13, installed: 0.0.14]
      - enum34 [required: Any, installed: 1.1.6]
      - mbstrdecoder [required: >=0.2.2, installed: 0.2.2]
        - six [required: >=1.10, installed: 1.10.0]
      - python-dateutil [required: >=2.6.1, installed: 2.6.1]
        - six [required: >=1.5, installed: 1.10.0]
      - pytz [required: >=2017.2, installed: 2017.2]
      - six [required: >=1.10, installed: 1.10.0]
  - typepy [required: >=0.0.14, installed: 0.0.14]
    - enum34 [required: Any, installed: 1.1.6]
    - mbstrdecoder [required: >=0.2.2, installed: 0.2.2]
      - six [required: >=1.10, installed: 1.10.0]
    - python-dateutil [required: >=2.6.1, installed: 2.6.1]
      - six [required: >=1.5, installed: 1.10.0]
    - pytz [required: >=2017.2, installed: 2017.2]
    - six [required: >=1.10, installed: 1.10.0]
  - voluptuous [required: Any, installed: 0.10.5]
```

**Comment by thombashi** [comment] 2017-07-30 15:29
Thank you for your additional information.

Unfortunately, I could not reproduce the problem at `Python 2.7.5` with older package version  (`pip`/`setuptools`) environment.

If you have opportunity to clean installation `tcconfig` to the environment in the future,
could you execute `pip install` command with verbose option (`-vvv`)?
The output might help to solve the problem.

**Comment by thombashi** [comment] 2017-08-03 14:40
I've changed version dependency package installation to using ``setuptools`` feature at ``tcconfig 0.12.2``.
I'm not sure this fix the problem though.

**Comment by dastergon** [comment] 2017-08-09 18:17
I can confirm that I have installed successfully the latest`tcconfig` package in different servers via pip.

**Comment by thombashi** [comment] 2017-08-10 16:11
@dastergon 
Thank you for confirming.

@fjarrett 
I'll close the issue for now.
Feel free to reopen.

**Closed by thombashi** 2017-08-10 16:11 UTC
