### ISSUE TITLE
Cannot delete rules

### ISSUE THREAD

**Issue by pxsalehi** [thombashi/tcconfig#93] opened 2018-01-10 18:41 UTC
After adding latency, I cannot clear up all rules using `tcdel -d DEVICE --all` as specified in the doc. I am using v0.17.1. Removing everything (root) using tc works and afterwards tcshow shows no rules.

**Comment by thombashi** [comment] 2018-01-15 14:08
@pxsalehi 

Thank you for your report.
Could you write down the command sequence to reproduce the issue?
I could not reproduce the issue in my environment,

**Comment by pxsalehi** [comment] 2018-01-17 10:09
Start with `sudo tcset -d eth0 --delay 100`
After this `tcshow -d eth0` shows:

```
{
    "eth0": {
        "outgoing": {
            "protocol=ip": {
                "filter_id": "800::800",
                "delay": "100.0ms",
                "rate": "10G"
            }
        },
        "incoming": {}
    }
}
```

Issuing `sudo tcdel -d eth0 --all` results in:
```
usage: tcdel [-h] [--version] [--tc-command | --tc-script] [--debug | --quiet]
             [--stacktrace] -d DEVICE [--ipv6]
tcdel: error: unrecognized arguments: --all
```
and tcshow still gives the same output. However, I can remove everything using 
`sudo  tc qdisc del dev eth0 root`

I am using tcconfig on a Docker container with Ubuntu 16.04.2 LTS.

**Comment by thombashi** [comment] 2018-01-17 14:58
Thank you for your information.

Could you re-check your tcconfig version with `--version` option?
You had described the version is `0.17.1`, but `tcconfig 0.17.1` have the `--all`/`-a` option.

```
# tcdel --version
tcdel 0.17.1
# tcdel -h
usage: tcdel [-h] [--version] [--tc-command | --tc-script] [--debug | --quiet]
             [--stacktrace] -d DEVICE [-a] [--id FILTER_ID]
             [--direction {outgoing,incoming}] [--network DST_NETWORK]
             [--src-network SRC_NETWORK] [--port DST_PORT]
             [--src-port SRC_PORT] [--ipv6]
...
```

**Comment by pxsalehi** [comment] 2018-01-17 15:18
```
ubuntu@broker-1:~$ tcdel --version
tcdel 0.17.1
ubuntu@broker-1:~$ tcdel -h
usage: tcdel [-h] [--version] [--tc-command | --tc-script] [--debug | --quiet]
             [--stacktrace] -d DEVICE [--ipv6]

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --tc-command          display tc commands to be executed and exit. these
                        commands are not executed.
  --tc-script           generate a script file that described tc commands
                        which equivalent with execution tcconfig command. the
                        script can be execute without tcconfig package
                        installation.
  --debug               for debug print.
  --quiet               suppress execution log messages.

Debug:
  --stacktrace          print stack trace for debug information. --debug
                        option required to see the debug print.

Traffic Control:
  -d DEVICE, --device DEVICE
                        network device name (e.g. eth0)
  --ipv6                Display IPv6 shaping rules. Defaults to show IPv4
                        shaping rules.

Issue tracker: https://github.com/thombashi/tcconfig/issues
```
I installed it from here:
https://github.com/thombashi/tcconfig/releases/download/v0.17.1/tcconfig_0.17.1_amd64.deb

**Comment by thombashi** [comment] 2018-01-20 17:19
@pxsalehi 
Thank you for additional information.

I had created the deb package improperly (especially for `tcdel` command).
Please try `tcconfig 0.17.2` deb package which fixes packaging problem.
https://github.com/thombashi/tcconfig/releases/download/v0.17.2/tcconfig_0.17.2_amd64.deb

**Comment by thombashi** [comment] 2018-02-05 13:38
@pxsalehi 

I'll close the issue.
Feel free to reopen if you still have any problems.

**Closed by thombashi** 2018-02-05 13:38 UTC
Labels: bug
