### ISSUE TITLE
Script's rules don't change class IDs.

### ISSUE THREAD

**Issue by user-name-is-taken** [thombashi/tcconfig#100] opened 2018-07-30 16:27 UTC
tcset must change the class IDs when using the --add parameter. When running tcset commands, this works:
```
USER@MACHINE ~/ $ tcshow eth5
{
    "eth5": {
        "outgoing": {},
        "incoming": {}
    }
}
USER@MACHINE ~/ $ sudo tcset --loss 4 --add --network 192.168.4.0/24 eth5
USER@MACHINE ~/ $ sudo tcset --loss 2 --add --network 192.168.2.0/24 eth5
USER@MACHINE ~/ $ tcshow eth5
{
    "eth5": {
        "outgoing": {
            "dst-network=192.168.4.0/24, protocol=ip": {
                "loss": 4,
                "rate": "32G",
                "filter_id": "800::800"
            },
            "dst-network=192.168.2.0/24, protocol=ip": {
                "loss": 2,
                "rate": "32G",
                "filter_id": "800::801"
            }
        },
        "incoming": {}
    }
}
```
<p>
As you can see above, tcshow shows that there are different rules for the % of dropped packets. 
</p>
<hr />
<p>
However,  scripts generated with the --tc-script parameter don't do this:
</p>
<pre>
<code>
 USER@MACHINE ~/ $ tcshow eth5
{
    "eth5": {
        "outgoing": {},
        "incoming": {}
    }
}
 USER@MACHINE ~/ $ sudo tcset --loss 2 --add --network 192.168.2.0/24 --tc-script eth5
[INFO] tcconfig: written a tc script to 'tcset_eth5.sh'
 USER@MACHINE ~/ $ mv tcset_eth5.sh tcset_2.sh
 USER@MACHINE ~/ $ sudo ./tcset_2.sh
 USER@MACHINE ~/ $ sudo tcset --loss 4 --add --network 192.168.4.0/24 --tc-script eth5
[INFO] tcconfig: written a tc script to 'tcset_eth5.sh'
 USER@MACHINE ~/ $ mv tcset_eth5.sh tcset_4.sh
 USER@MACHINE ~/ $ sudo ./tcset_4.sh 
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
 USER@MACHINE ~/ $ tcshow eth5
{
    "eth5": {
        "outgoing": {
            "dst-network=192.168.2.0/24, protocol=ip": {
                "filter_id": "800::800",
                "loss": 2,
                "rate": "32G"
            },
            "dst-network=192.168.4.0/24, protocol=ip": {
                "filter_id": "800::801",
                "loss": 2,
                "rate": "32G"
            }
        },
        "incoming": {}
    }
}
</code>
</pre>
As you can see, both networks are set to a loss of 2% where 192.168.2.0/24 should be 2% and 192.168.4.0/24 should be 4%.

**Comment by user-name-is-taken** [comment] 2018-07-30 18:56
I closed this issue because I added the wrong shell output, this is still an issue

**Comment by thombashi** [comment] 2018-08-05 17:54
@user-name-is-taken 
Thank you for your report.

I had fixed the problem at `tcconfig 0.20.0`
The cause of the problem is the handle-id conflict for tc rules.
`tcset` avoid this handle-id conflicts by checking existing handle-ids.
While scripts generated by `--tc-script` does not check the conflicts.
I had changed handle-id generation algorithm to be reduced the probability of conflicts.

```
$ ./tcset_eth0_loss2.0.sh
$ ./tcset_eth0_loss4.0.sh
RTNETLINK answers: File exists
RTNETLINK answers: File exists
$ tcshow eth0
{
    "eth0": {
        "outgoing": {
            "dst-network=192.168.2.0/24, protocol=ip": {
                "filter_id": "800::800",
                "loss": 2,
                "rate": "1G"
            },
            "dst-network=192.168.4.0/24, protocol=ip": {
                "filter_id": "800::801",
                "loss": 4,
                "rate": "1G"
            }
        },
        "incoming": {}
    }
}
```

**Comment by user-name-is-taken** [comment] 2018-08-10 17:45
Works on small tests. Thank you.

**Comment by thombashi** [comment] 2018-08-11 05:07
Thank you for your confirmation.
I'll close the issue then.

**Closed by thombashi** 2018-08-11 05:07 UTC
