### ISSUE TITLE
broken sqlite

### ISSUE THREAD

**Issue by tazhate** [thombashi/tcconfig#104] opened 2019-01-22 14:01 UTC
```
➜  ~ sudo tcset tctest --docker --direction incoming --rate 100Kbps

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/simplesqlite/core.py", line 545, in insert_many
    self.connection.executemany(query, records)
sqlite3.IntegrityError: UNIQUE constraint failed: if_index.peer_ifindex

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tcset", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tcconfig/tcset.py", line 347, in main
    return TcSetMain(options).run()
  File "/usr/local/lib/python3.6/dist-packages/tcconfig/tcset.py", line 227, in run
    for device in self._fetch_tc_target_list():
  File "/usr/local/lib/python3.6/dist-packages/tcconfig/_main.py", line 35, in _fetch_tc_target_list
    self._dclient.create_veth_table(container)
  File "/usr/local/lib/python3.6/dist-packages/tcconfig/_docker.py", line 139, in create_veth_table
    return_code = self.__create_ifindex_table(container_info.name)
  File "/usr/local/lib/python3.6/dist-packages/tcconfig/_docker.py", line 218, in __create_ifindex_table
    peer_ifindex=int(peer_ifindex_prefix_regexp.sub("", peer_ifindex)),
  File "/usr/local/lib/python3.6/dist-packages/simplesqlite/model.py", line 197, in insert
    cls.__connection.insert(cls.get_table_name(), record)
  File "/usr/local/lib/python3.6/dist-packages/simplesqlite/core.py", line 499, in insert
    self.insert_many(table_name, [record])
  File "/usr/local/lib/python3.6/dist-packages/simplesqlite/core.py", line 554, in insert_many
    + "  records={}\n".format(records[:2])
simplesqlite.error.OperationalError: /usr/local/lib/python3.6/dist-packages/simplesqlite/model.py(197) insert: failed to execute query:
  query=INSERT INTO if_index VALUES (?,?,?,?)
  msg='UNIQUE constraint failed: if_index.peer_ifindex'
  db=:memory:
  records=[['tazthink', 20, 'veth4e6461a7', 3]]

```

**Comment by thombashi** [comment] 2019-01-22 16:08
@tazhate 
Thank you for your report.

Unfortunately, I could not reproduce the issue in my environments.

Could you execute the below command with `tcconfig 21.6` and past the full output?

    sudo tcset tctest --docker --direction incoming --rate 100Kbps --debug --debug-query

(I had added an option and messages for debug print at that version.)

In addition, please let me know your environments:

    - OS
    - docker version
    - Python version
    - iproute2 version
    - etc.

**Comment by thombashi** [comment] 2019-01-24 14:42
@tazhate 
Thank you for additional information. It would be a great help.

Could you execute the following command at the docker host and post the output here?

```
ip link show type veth
```

Looks like parsing the output of the above command failed and leading to the `tcset` error.

**Comment by thombashi** [comment] 2019-02-03 14:56
@tazhate 
I had added some error handling at `tcconfig 0.21.7`.
It could be a work around the issue.
May still error message appears.

**Comment by thombashi** [comment] 2019-04-14 09:13
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.

**Closed by thombashi** 2019-04-14 09:13 UTC
